[mgr]
prepend_keymap = [
  { on = "M", run = "plugin toggle-pane max-preview", desc = "Maximize/restore preview pane" },
  { on = "f", run = "plugin jump-to-char", desc = "Jump to char" },
  { on = "l", run = "plugin smart-enter", desc = "Enter or open" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  { on = ["c", "m"], run = "plugin chmod", desc = "Chmod on selected" },
  { on = "p", run = "plugin smart-paste", desc = "Smart paste" },
  { on = ["g", "r"], run = "plugin cd-git-root", desc = "Jump to git root" },
  { on = ["y", "p"], run = "plugin relative-path", desc = "Copy relative path" },
  { on = ["m", "c"], run = "linemode size_mtime", desc = "Linemode: size+mtime" },
  { on = [",", "m"], run = ["sort mtime --reverse=no"], desc = "Sort by modified time" },
  { on = [",", "M"], run = ["sort mtime --reverse=yes"], desc = "Sort by modified time (reverse)" },
  { on = [",", "b"], run = ["sort btime --reverse=no"], desc = "Sort by birth time" },
  { on = [",", "B"], run = ["sort btime --reverse=yes"], desc = "Sort by birth time (reverse)" },
  { on = [",", "s"], run = ["sort size --reverse=no"], desc = "Sort by size" },
  { on = [",", "S"], run = ["sort size --reverse=yes"], desc = "Sort by size (reverse)" },
]