theme = 'carbon'

[editor]
color-modes = true
line-number = "relative"
mouse = true
trim-trailing-whitespace = true
completion-replace = true
rulers = [100]
end-of-line-diagnostics = "hint"
# TODO: Enable rainbow brackets when upgrading to Helix nightly or next stable release (merged July 2024)
# rainbow-brackets = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "spacer", "separator", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "workspace-diagnostics", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "hint"

[editor.indent-guides]
render = true
character = "⏽"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
"'" = "'"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 300000

[keys.normal]
d = "delete_selection_noyank"
C-q = [
  ':sh rm -f /tmp/helix-yazi-chooser',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/helix-yazi-chooser',
  ':insert-output echo "\\x1b[?1049h\\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/helix-yazi-chooser}',
  ':redraw',
]

[keys.normal.space.f]
r = ":reload-all"
