(require-builtin steel/random as rand::)
(require "cogs/keymaps.scm")
(require (prefix-in helix. "helix/commands.scm"))
(require (prefix-in helix.static. "helix/static.scm"))
(require "helix/configuration.scm")
(require "splash.scm")
(require "focus.scm")

;; Load file watcher for automatic reload
(require "helix-file-watcher/file-watcher.scm")
(spawn-watcher)

;; Comment out theme override to respect user's config.toml theme
;; (define possible-themes '("focus_nova"))
;; (define (select-random lst)
;;   (let ([index (rand::rng->gen-range 0 (length lst))]) (list-ref lst index)))
;; (define (randomly-pick-theme options)
;;   (helix.theme (select-random options)))
;; (randomly-pick-theme possible-themes)
(recentf-snapshot)
(keymap (global)
        (normal (C-r (f ":recentf-open-files")) (space (l ":load-buffer") (o ":eval-sexpr"))))
(define scm-keybindings (hash "insert" (hash "ret" ':scheme-indent "C-l" ':insert-lambda)))
(define standard-keybindings (deep-copy-global-keybindings))
(define file-tree-base (deep-copy-global-keybindings))
(merge-keybindings standard-keybindings scm-keybindings)
(merge-keybindings file-tree-base FILE-TREE-KEYBINDINGS)
(set-global-buffer-or-extension-keymap (hash "scm" standard-keybindings FILE-TREE file-tree-base))
;; Comment out overrides to respect user's config.toml settings
;; (file-picker (fp-hidden #f))
;; (cursorline #t)
;; (soft-wrap (sw-enable #t))
;; (randomly-pick-theme possible-themes)
(define-lsp "steel-language-server" (command "steel-language-server") (args '()))
(define-lsp "rust-analyzer" (config (experimental (hash 'testExplorer #t))))
(define-language "scheme"
                 (formatter (command "raco") (args '("fmt" "-i")))
                 (auto-format #true)
                 (language-servers '("steel-language-server")))
(when (equal? (command-line) '("hx"))
  (show-splash))